#%RAML 1.0 DataType

displayName: getRoutes.
description: This data type is used to reterive routes.
type: object
properties:
  location:
    type: array
    items:
      properties:
        originLocation.locationCode:
          type: string
          required: true
          description: The departure location code
        destinationLocation.locationCode:
          type: string
          required: true
          description: The arrival location code
       

  #responses as array 
   
  
    
   
  
    
    



    

  
  


  


  

    



